### ISSUE TITLE
EntryRepository.java missing @Query for findByBlogUserLoginOrderByDateDesc()

### ISSUE THREAD

**Issue by Jon007** [mraible/jhipster4-demo#12]
EntryRepository.java findByBlogUserLoginOrderByDateDesc() returns no data, this appears to be because it is missing the @Query definition.

**Comment by mraible** [comment]
You have to make sure and enter some data for the current user before you'll see their data. Can you please provide steps to reproduce if you do that and it still doesn't work?

**Comment by Jon007** [comment]
sure I did add entries for both admin and user, no entries are visible after change to findByBlogUserLoginOrderByDateDesc until an @query is added

where is the query defined if there is no @query ? 
I will eat my hat if the framework is really capably of making up a query just from the function name findByBlogUserLoginOrderByDateDesc

**Comment by mraible** [comment]
Yep: Spring Data JPA will generate a query from the method name. ;)

https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods

**Comment by Jon007** [comment]
oh right, yes the documentation 3.4.2. Query creation is impressive.

now I see there is
```
2018-04-30 23:40:56.649 ERROR 2248 --- [ XNIO-13 task-3] o.z.p.spring.web.advice.AdviceTrait      : Internal Server Error

java.lang.RuntimeException: Uncompilable source code - Erroneous sym type: com.mycompany.myapp.repository.EntryRepository.findByBlogUserLoginOrderByDateDesc
```

**Comment by Jon007** [comment]
Actually that was with the call in EntryResource.java
`				Page<Entry> page = entryRepository.findByBlogUserLoginOrderByDateDesc(SecurityUtils.getCurrentUserLogin(), pageable);
`
which is still the version in github though Netbeans does flag it up as incompatible types: `Optional<String> cannot be converted to String`

**Comment by Jon007** [comment]
so the line in EntryResource.java and in the [docs](http://gist.asciidoctor.org/?github-mraible/jhipster4-demo//README.adoc) would become:
`				Page<Entry> page = entryRepository.findByBlogUserLoginOrderByDateDesc(SecurityUtils.getCurrentUserLogin().get(), pageable);
`
then it works

**Comment by mraible** [comment]
Right. I'm guessing you're using a newer version of JHipster than the one that's in this repo? This repo uses JHipster v[4.3.0](https://github.com/mraible/jhipster4-demo/blob/master/.yo-rc.json#L3). I did do an upgrade to 4.13.3 in https://github.com/mraible/jhipster4-demo/pull/10, but didn't merge it to master because I haven't updated the tutorial yet.

**Comment by Jon007** [comment]
Oh right, yes I'm on v4.14.3
I see that now (and would explain some other issues)..

I got here from the prominent link on the Hipster home page > Learn JHipster In 12 Minutes With Matt Raible > actually open that in youtube to see it properly and eventually notice the doc > [tutorial gist](https://www.youtube.com/redirect?redir_token=wqV_i6mwdEKXH-sKSX2RVaf3Y3J8MTUyNTIxNzI0OEAxNTI1MTMwODQ4&event=video_description&v=XRREt1KB4Y8&q=http%3A%2F%2Fgist.asciidoctor.org%2F%3Fgithub-mraible%2Fjhipster4-demo%2F%2FREADME.adoc)

Which seemed like a logical sequence for someone new to hipster .. the hipster home page of course doesn't advise installing an older version before running through the tutorial, 
I see now the document does advise 4.3.0 however one only finds the document after already installing and trying to follow the video...

**Comment by mraible** [comment]
Yes, I should update the tutorial. I'll try to do it this week.
