### ISSUE TITLE
login issue with default users 'admin' and 'user'

### ISSUE THREAD

**Issue by ksrkon** [mraible/jhipster4-demo#13]
Hi, I am trying to run the demo blog application. I did followed everything as per process. I am trying login with the defult users like admin/admin and user/user, but i am unable to login and saying that failed to login.

Anything wrong in the setup or something else please let me know.

Thanks

Screen:
![capture](https://user-images.githubusercontent.com/7062999/39496594-b6d14db6-4d64-11e8-9604-58bddb0d4748.PNG)

**Comment by mraible** [comment]
Are you running it locally? Is there anything in your logs?

**Comment by ksrkon** [comment]
Yes, am running locally. Here i am attaching console info and log file.

![untitled](https://user-images.githubusercontent.com/7062999/39525320-3f248b3e-4de1-11e8-9fbe-2d9aa863f0b0.png)
[yarn-error.log](https://github.com/mraible/jhipster4-demo/files/1967381/yarn-error.log)

**Comment by mraible** [comment]
It looks like you don't have anything running on port 8080. You need to run `./mvnw` in one terminal, and `yarn start` in the other.
