### ISSUE TITLE
Unable to launch application after downloading it

### ISSUE THREAD

**Issue by yihfenglow** [mraible/jhipster4-demo#5]
Hi,

I tried downloading the application and launching BlogApp via IntelliJ per the video https://youtu.be/XRREt1KB4Y8. 

The application seems to have started correctly:

	Application 'blog' is running! Access URLs:
	Local: 		http://localhost:8080
	External: 	http://172.21.161.134:8080
	Profile(s): 	[swagger, dev]

However, when I go to http://localhost:8080/, all I get is a completely blank screen.

Attached please find screenshot of the blank screen. Also, please find the html file returned (retrieved via right click>view source).

Any advice you could provide would be very much appreciated! Thanks very much in advance!

![jhipster-blank](https://cloud.githubusercontent.com/assets/25000037/24943941/25cd43e8-1f9c-11e7-9d34-bfaabad6fb0d.jpg)

**Comment by yihfenglow** [comment]
[jhipster-blank.html.txt](https://github.com/mraible/jhipster4-demo/files/915576/jhipster-blank.html.txt)

**Comment by mraible** [comment]
Did you run `npm install`? If so, running `yarn start` should work.

Related discussion: https://groups.google.com/forum/#!topic/jhipster-dev/PuI2YAaNEK8
