### ISSUE TITLE
Date Check failed when creating an entry 

### ISSUE THREAD

**Issue by LeducH** [mraible/jhipster4-demo#7]
First of all thank you for this tutorial. 

After following the steps 'Generate Entities' I started to get an error when validating the date for an entriy . 
I am sure the field is none empty.
![screenshot from 2017-10-25 12-56-59](https://user-images.githubusercontent.com/25816738/31995341-521078e4-b984-11e7-866f-94d93b948e90.png)

What seems to be the issue? I assume the front end sends just an empty string

**Comment by mraible** [comment]
Can you please run `yo jhipster:info` and paste it here as a comment? That should give me the information I need to try and reproduce this issue.

**Comment by LeducH** [comment]
Of course I can add the output. Do also need the oout put on the server ?

    Welcome to the JHipster Information Sub-Generator
    
    ##### **JHipster Version(s)**
    
    ```
    my-new-blog@0.0.0 /home/user/Projects/myNewBlog
    ├── generator-jhipster@4.10.0 
    └── UNMET PEER DEPENDENCY popper.js@^1.11.0
    
    ```
    
    
    ##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
    
    
    <details>
    <summary>.yo-rc.json file</summary>
    <pre>
    {
      "generator-jhipster": {
        "promptValues": {
          "packageName": "com.mycompany.myapp",
          "nativeLanguage": "en"
        },
        "jhipsterVersion": "4.10.0",
        "baseName": "myNewBlog",
        "packageName": "com.mycompany.myapp",
        "packageFolder": "com/mycompany/myapp",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "hibernateCache": "ehcache",
        "clusteredHttpSession": false,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSocialSignIn": false,
        "enableSwaggerCodegen": false,
        "jwtSecretKey": "replaced-by-jhipster-info",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "yarn",
        "applicationType": "monolith",
        "testFrameworks": [
          "gatling",
          "protractor"
        ],
        "jhiPrefix": "jhi",
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": [
          "en",
          "de"
        ]
      }
    }
    </pre>
    </details>
    
    
    ##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
    
    <details>
    <summary>JDL entity definitions</summary>
    
    <pre>
    entity Blog (blog) {
      name String required minlength(3),
      handle String required minlength(2)
    }
    entity Entry (entry) {
      title String required,
      content byte[] required,
      date ZonedDateTime required
    }
    entity Tag (tag) {
      name String required minlength(2)
    }
    
    relationship ManyToOne {
      Blog{user(login)} to User,
      Entry{blog(name)} to Blog
    }
    relationship ManyToMany {
      Entry{tag(name)} to Tag{entry}
    }
    
    paginate Entry, Tag with infinite-scroll
    
    </pre>
    </details>
    
    
    ##### **Environment and Tools**
    
    java version "1.8.0_151"
    Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
    Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
    
    git version 2.7.4
    
    node: v6.11.4
    
    npm: 3.10.10
    
    yeoman: 2.0.0
    
    yarn: 1.2.1

**Comment by mraible** [comment]
Sure, server output would be great!

**Comment by LeducH** [comment]
here it comes 

    2017-10-25 12:56:57.045  WARN 13011 --- [  XNIO-4 task-1] .m.m.a.ExceptionHandlerExceptionResolver : 
    Resolved exception caused by Handler execution: org.springframework.web.bind.MethodArgumentNotValidException: 
    Validation failed for argument at index 0 in method: 
    public org.springframework.http.ResponseEntity<com.mycompany.myapp.domain.Entry> 
    com.mycompany.myapp.web.rest.EntryResource.createEntry(com.mycompany.myapp.domain.Entry) 
    throws java.net.URISyntaxException, with 1 error(s): [Field error in object 'entry' on field 'date': 
    rejected value [null]; codes [NotNull.entry.date,NotNull.date,NotNull.java.time.ZonedDateTime,NotNull]; 
    arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [entry.date,date]; 
    arguments []; default message [date]]; default message [may not be null]]

**Comment by LeducH** [comment]
after checking the browser console I realized that the the request sends out an empty field for the JSON object. 

```
Host: localhost:9000
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTUxMTUxNjA2NX0.fGAFtp5qP3-ZmwOLlN5yxwdlC0rdZB905u4tfNXCYn-yryhZ56ubQoLedUBw2BCb8-p03DI-ZVT8uFESW124PQ
Referer: http://localhost:9000/
Content-Length: 86
Cookie: io=OPyrD96YniRyMkMQAAAA
Connection: keep-alive

```

body 

```
{
  "title": "Meditation on the  Force",
  "content": "New conternt",
  "date": null
}
```

therefore I was wondering what the architecture of jhipster is and where the front end can be adjusted and corrected?

**Comment by LeducH** [comment]
It seems that the even when I edit the request body and write a some string into field I still get an error 
request 
```
Host: localhost:9000
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTUxMTUxNjA2NX0.fGAFtp5qP3-ZmwOLlN5yxwdlC0rdZB905u4tfNXCYn-yryhZ56ubQoLedUBw2BCb8-p03DI-ZVT8uFESW124PQ
Referer: http://localhost:9000/
Content-Length: 396
Cookie: io=GJRx_2E8nyprHxAIAAAE
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

```
Response 
```
x-powered-by: Express
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
date: Thu, 26 Oct 2017 10:47:52 GMT
connection: close
x-content-type-options: nosniff
content-type: application/problem+json
x-application-context: myNewBlog:swagger,dev:8080
transfer-encoding: chunked
```

body 

```
{
  "title": "Here",
  "content": "The Force",
  "date": "Feb 01, 2007, 5:00:00 pm",
  "blog": {
    "id": 1,
    "name": "yoda",
    "handle": "admin",
    "user": {
      "id": 4,
      "login": "user",
      "firstName": "User",
      "lastName": "User",
      "email": "user@localhost",
      "activated": true,
      "langKey": "en",
      "imageUrl": "",
      "resetDate": null
    }
  }
}
```

error message
```
2017-10-26 12:47:52.488  WARN 15050 --- [  XNIO-3 task-6] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Can not deserialize value of type java.time.ZonedDateTime from String "Feb 01, 2007, 5:00:00 pm": Text 'Feb 01, 2007, 5:00:00 pm' could not be parsed at index 0; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.time.ZonedDateTime from String "Feb 01, 2007, 5:00:00 pm": Text 'Feb 01, 2007, 5:00:00 pm' could not be parsed at index 0
 at [Source: java.io.PushbackInputStream@160e0e5f; line: 4, column: 11] (through reference chain: com.mycompany.myapp.domain.Entry["date"])
````

It seems like there is no way around then manually editing the classes. I looked into the 

`src/main/webapp/app/entities/entry/entry-detail.component.html`

and found the part 

```
  <dt><span jhiTranslate="myNewBlogApp.entry.date">Date</span></dt>
        <dd>
            <span>{{entry.date | date:'medium'}}</span>
        </dd>
```

but I missing where the logic is that handles this object. Could you tell me where this happens.

**Comment by mraible** [comment]
I'm on vacation for the next few days. I'll look into this when I return next week.

**Comment by mraible** [comment]
I tried creating this project with JHipster 4.10.2 today and didn't have any issues. I created PR #8 with all my changes so far. You might want to compare your `entry-dialog.component.html` to the [`entry-dialog.component.html` from this PR](https://github.com/mraible/jhipster4-demo/blob/upgrade-4.10.2/src/main/webapp/app/entities/entry/entry-dialog.component.html).

If you look at the screenshot below, you'll notice my date has a date and time, whereas yours does not. 

<img width="847" alt="screen shot 2017-10-31 at 1 37 10 pm" src="https://user-images.githubusercontent.com/17892/32245399-4276976c-be41-11e7-8030-304499ea3939.png">

Your date field should look similar to the following:

```html
<input id="field_date" type="datetime-local" class="form-control" name="date" 
       [(ngModel)]="entry.date" required  />
```

**Comment by LeducH** [comment]
Thank you for your reply. but I checked this file, too and it says 

```
   <div class="d-flex">
                <input id="field_date" type="datetime-local" 
class="form-control" name="date" [(ngModel)]="entry.date"
                required  />
   </div>
```

I was using firefox and as It seems only chrome implements the date input into the fields. Therefore other browsers such as Firefox have just a plain textfield. now after some research I found out what it iso format  for dates is for Json objects and could add entries by having the correct format (namely  yyyy-mm-ddThh:mm:ss). 
In any case the error message "date field is empty" is wrong if the format is just off. therefore you should check your validation in the front end and correct the error message or also consider other browsers when testing. 
Even in chrome if you only select the date you get the same error message even tough the field is clearly not empty.  

I hope that helps if you want me to help out let me know. I am  unsure how you build the front end but if you give me some hints I might be able to fix it.

**Comment by mraible** [comment]
I'm closing this issue here since it seems more appropriate to have it in the JHipster project. https://github.com/jhipster/generator-jhipster/issues/6711
